### PR TITLE
Implement "Countup" text format

### PR DESCRIPTION
**Pull request by kadamwhite**
With this PR, you can now annotate text in the project as a "Count-up number" and then it will count in once it scrolls into view on the frontend.

Also sneaks in a change to make the editor text sans-serif.

countup

### CODE REVIEW

**Comment by kadamwhite** [comment]
Once we get this into public review we can iterate on the animation timing, 1 second felt "visible but not annoyingly slow".

**Review by mattwatsoncodes — COMMENTED** [review]
**Edge case for consideration** 

The count-up removes some of the original number formatting by _adding in commas_. 

It also removes non-numeric characters and commas, however I think the non-numeric character removal and comma removal is fine though as you could just highlight the numberic part of the text, so this can easily be mitigated.

**Before:** 
CleanShot 2024-03-20 at 09 36 02@2x

**After**
CleanShot 2024-03-20 at 09 36 31@2x

**Comment by kadamwhite** [comment]
Good point. The designs have commas so I would put it to WMF whether that is OK or not. Hello

**Review by mattwatsoncodes — APPROVED** [review]
Approving. If the existing designs have numbers then we only have to select numeric text and it will behave as expected.

We can flag to WMF and if we need to alter we can introduce those changes.

**Review by goldenapples — APPROVED** [review]

**Pull request merged**
